spring:
  datasource:
    url: jdbc:mysql://localhost:3306/server
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
server:
  port: 8181
